version: "3.8"

services:
  app:
    build:
      context: ./
    image: web4:app
    ports:
      - "3000:8081"
    volumes:
      - "./secrets:/run/secrets"
      - ./:/app
    env_file:
      - "./secrets/postgres.env"
    depends_on: [postgres-db]

  postgres-db:
    image: postgres
    volumes:
      - "./secrets:/run/secrets"
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - "./secrets/postgres.env"
volumes:
  postgres-data:


